In [ ]:
# 확률분포

# 동전을 한번 던져 나올수 있는 경우의 확률분포
# (앞1/2, 뒤1/2)

# 동전을 두번 던져 나올수 있는 경우의 확률분포
#(앞,앞),(앞,뒤),(뒤,앞),(뒤,뒤)
#  1/4    1/4    1/4     1/4
# 앞의 값 1, 뒤의 값 0일때의 값의 합 분포
#   2          1          0
#  1/4        2/4        1/4

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

def fact(n):
    ret = 1
    while n>1:
        ret *= n
        n -= 1
    return ret

def fact_r(n):
    if n==2:
        return n
    return fact_r(n-1)*n

def perm_f(n, r):
    return fact(n)/fact(n-r)

def combi_f(n, r):
    return fact(n)/(fact(n-r)*fact(r))

def count_with_replacement_order(pool, sel_count):  # all
    if sel_count == 1:
        return len(pool), [[x] for x in pool]
    a, b = count_with_replacement_order(pool, sel_count-1)
    r = []
    for x in pool:
        for b_i in b:
            r.append(b_i+[x])
    return len(r), r    

def perm_pool(pool, r):
    if r == 1:
        return len(pool), [[x] for x in pool]
    ret = []
    for x in pool:
        pool_copy = [y for y in pool]
        pool_copy.remove(x)
        a, b = perm_pool(pool_copy, r-1)
        for b_i in b:
            ret.append(b_i+[x])
    return len(ret), ret

def combi_pool(pool, r):
    a , b = perm_pool(pool, r)
    r = []
    for b_i in b:
        r.append(set(b_i))
    f = []
    for r_i in r:
        if r_i not in f:
            f.append(r_i)
    return len(f), f

In [12]:
x = count_with_replacement_order([1,0],2)
print(x)
x_array = np.array(x[1])
print(x_array)
x_array1 = np.sum(x_array,axis=1)
x_array2 = np.unique(x_array1, return_counts=True)
print(x_array2[0])
print(x_array2[1]/len(x_array1))

(4, [[1, 1], [0, 1], [1, 0], [0, 0]])
[[1 1]
 [0 1]
 [1 0]
 [0 0]]
[0 1 2]
[0.25 0.5  0.25]
