In [6]:
import numpy as np

In [11]:
a1 = np.array([1,2,3,4,5])
print([1,2,3,4,5])
print(a1)
print(type(a1))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [29]:
a2 = np.arange(10)
print(a2)

a3 = np.arange(3,100,3)
print(a3)

# 1에서부터 10아래 0.5씩 증가하는 숫자, step=0.5
a4 = np.arange(1.3,10,0.5)
print(a4)

[0 1 2 3 4 5 6 7 8 9]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8 5.3 5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


In [48]:
a4 = np.linspace(0,10,15)
print(a4)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [53]:
a5 = np.zeros(5,int)
print(a5)

a6 = np.ones(5,int)
print(a6)
a6.astype(np.float64)

[0 0 0 0 0]
[1 1 1 1 1]


array([1., 1., 1., 1., 1.])

In [55]:
lista = [1,2,3.5,4.2]
a7 = np.array(lista)
print(a7)

listb = [1,2,'abc','def']
a8 = np.array(listb)
print(a8)
# a8.astype(np.int64)

[1.  2.  3.5 4.2]
['1' '2' 'abc' 'def']


In [61]:
print(a7.dtype)
print(a7.ndim)
print(a7.shape)
print(a7.size)

print(a7.itemsize)
print(a7.data)

float64
1
(4,)
4
8


In [67]:
a10 = np.arange(10,100,5)
print(a10)

# 특정인덱스
print(a10[3])
# 스타트, 스탑
print(a10[0:3])
# 스타트, 스탑, 스텝
print(a10[0:3:2])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
25
[10 15 20]
[10 20]


In [69]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[[1,3,7]])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 45]


In [75]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[a10%10 == 5])
x = (a10%10 == 5)
print(x.shape)
print(a10.shape)
print(a10[x])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 35 45 55 65 75 85 95]
(18,)
(18,)
[15 25 35 45 55 65 75 85 95]


In [91]:
a1 = np.arange(5)
a2 = np.arange(10,15)
print(a1)
print(a2)
print('add:',a1+a2)
print(np.concatenate((a1,a2)))
print('sub:',a1-a2)
print('mul:',a1*a2)
print('div:',a1/a2)

[0 1 2 3 4]
[10 11 12 13 14]
add: [10 12 14 16 18]
[ 0  1  2  3  4 10 11 12 13 14]
sub: [-10 -10 -10 -10 -10]
mul: [ 0 11 24 39 56]
div: [0.         0.09090909 0.16666667 0.23076923 0.28571429]


In [92]:
help(np.broadcast)

Help on class broadcast in module numpy:

class broadcast(builtins.object)
 |  Produce an object that mimics broadcasting.
 |  
 |  Parameters
 |  ----------
 |  in1, in2, ... : array_like
 |      Input parameters.
 |  
 |  Returns
 |  -------
 |  b : broadcast object
 |      Broadcast the input parameters against one another, and
 |      return an object that encapsulates the result.
 |      Amongst others, it has ``shape`` and ``nd`` properties, and
 |      may be used as an iterator.
 |  
 |  See Also
 |  --------
 |  broadcast_arrays
 |  broadcast_to
 |  broadcast_shapes
 |  
 |  Examples
 |  --------
 |  
 |  Manually adding two vectors, using broadcasting:
 |  
 |  >>> x = np.array([[1], [2], [3]])
 |  >>> y = np.array([4, 5, 6])
 |  >>> b = np.broadcast(x, y)
 |  
 |  >>> out = np.empty(b.shape)
 |  >>> out.flat = [u+v for (u,v) in b]
 |  >>> out
 |  array([[5.,  6.,  7.],
 |         [6.,  7.,  8.],
 |         [7.,  8.,  9.]])
 |  
 |  Compare against built-in broadcasting:
 |  